[project]
name = "tmux-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse",
    "libtmux",
]

[project.scripts]
tmux-man = "main:main"
